

#██╗░░░██╗██╗░░░░░  ░░░░░░  ░██████╗░███████╗███╗░░██╗███████╗██████╗░░█████╗░████████╗░█████╗░██████╗░
#██║░░░██║██║░░░░░  ░░░░░░  ██╔════╝░██╔════╝████╗░██║██╔════╝██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗
#██║░░░██║██║░░░░░  █████╗  ██║░░██╗░█████╗░░██╔██╗██║█████╗░░██████╔╝███████║░░░██║░░░██║░░██║██████╔╝
#██║░░░██║██║░░░░░  ╚════╝  ██║░░╚██╗██╔══╝░░██║╚████║██╔══╝░░██╔══██╗██╔══██║░░░██║░░░██║░░██║██╔══██╗
#╚██████╔╝███████╗  ░░░░░░  ╚██████╔╝███████╗██║░╚███║███████╗██║░░██║██║░░██║░░░██║░░░╚█████╔╝██║░░██║
#░╚═════╝░╚══════╝  ░░░░░░  ░╚═════╝░╚══════╝╚═╝░░╚══╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝


#░█▀▀▄ █──█ 　 ░█▀▀▄ █▀▀ █▀▀█ █▀▀▄ ░█─── ─▀─ █▀▀▀ █──█ ▀▀█▀▀
#░█▀▀▄ █▄▄█ 　 ░█─░█ █▀▀ █▄▄█ █──█ ░█─── ▀█▀ █─▀█ █▀▀█ ──█──
#░▀▀▀─ ▄▄▄█ 　 ░█▄▄▀ ▀▀▀ ▀──▀ ▀▀▀─ ░█▄▄█ ▀▀▀ ▀▀▀▀ ▀──▀ ──▀──

#Welcome to Under Lava Generator Plugin Configuration, The Configuration file is so simple and simple-made for
#everyone to use. You just need to put the CORRECT block value to work. Otherwise it will print out with an error,
#But do not panic! I have put spigot block names link, so you can easily config without a pain. Also each part in the configuration
#fully explained and well-made.
#Remember, Feel free to request new features or report bugs to fix. You can contact me through Discord and Telegram.
#I don't have discord community yet - But if other developers like to work and contribute just contact me.
#It is more nice if you even donate me 1$, so much appreciated...
#Paypal: https://www.paypal.me/itzamirreza
#Discord: Dead_Light#1711
#Telegram: @ItzDead
#List of block names that you need to use for 1.13 until newest versions: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#List of block names that you need to use for 1.8 - 1.12.2 (before 1.13): https://helpch.at/docs/1.12.2/index.html?org/bukkit/Material.html
#List of biome names that you may need to use for 1.13 -> 1.16: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
#List of biomes names that you may need to use for 1.8 -> 1.12.2: https://neolumia.github.io/spigot-docs/1.12.2/org/bukkit/block/Biome.html
#----------V------------Config starts from here!------------V--------------#

#Plugin start enabling on startup - duo you can just remove or disable the plugin from other ways...
enable-plugin-on-startup: true

#The worlds that plugin does not work in.
#You can see default example and add your worlds
disabled-worlds:
  #- world
  #- world_nether
  - world_the_end
  #- AnyNameThatYourWorldHas

#Admin Commands Permission | DEFAULT: ulg.admin
#The default is ulg.admin but you can easily change it if it does make incompatibility with other plugins.
admin-permission: "ulg.admin"

#Generators part
generators-settings:
  #if you set permission to none, players won't need permission to use these generators | default is none | Ex: ulg.use
  permission: "none"
  generators:
  #Now you can add-remove your custom generators! Enjoy and PLEASE READ DESCRIPTIONS
  #Name of the block which is under the lava
  #be careful when i say under the lava, it means exactly the one which interact with water! (As it shows in gifs on spigot page)
  #Also NOTICE that Vertical Generators ARE NOT SUPPORTED till this version, but we will have plans to develop for newer versions.
    EMERALD_BLOCK:
      #The island level which is required for this generator. Right now, we support 5 island plugins:
      #FabledSkyBlock - BentoBox - ASkyBlock - uSkyBlock - SuperiorSkyblock2
      #Notes:
      #You need to install Levels Addon For BentoBox to work!
      #You have to disable FabledSkyblock ore generations to stop some conflicts
      required-island-level: 100
      #The biome which is required to let generation happen | default is false | List of BIOMEs provided in header of config
      #Example: required-biome: BEACHES
      #Names are provided in header
      required-biome: false
      blocks:
        #It/These can be only blocks, otherwise it wont work... Blocks will have a change of generating, between 1 - 100
        #You may ask how these percentages work, basically for each ore, a random number will generate between 0 - 100, and we will check if percentage is bigger or smaller than random generated number.
        #- Material:Percentage <---- Percentage must be between 1 - 100
        - IRON_ORE:5
        - DIAMOND_ORE:10
        - EMERALD_ORE:100
        - COAL_ORE:90
        #- WOOL:1
        #- COBBLESTONE:50

    REDSTONE_BLOCK:
      required-island-level: 0
      required-biome: PLAINS
      blocks:
        - REDSTONE_ORE:10
        - DIAMOND_BLOCK:90
        - BEDROCK:10
#        - GRASS_BLOCK:100 (1.13+) | -GRASS:100 (1.8+)



#Hope you enjoy this plugin, Remember your votings on my SPIGOTMC page is IMPORTANT to me, and i'll try to answer you ASAP.